name: pr-preview
concurrency: preview-${{ github.ref }}
on: 
    pull_request:
         types:
           - opened
           - synchronize

jobs:
   buildprpages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt

      - name: build-docs
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          action: deploy
